### ISSUE TITLE
working with JSP to evict DRY or not ?

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#10]
1) includes
or
2) sitemesh

?

**Comment by danielsoro** [comment]
I prefer sitemesh.

**Comment by helio-frota** [comment]
@danielsoro me too :+1:

**Comment by paulojribp** [comment]
Good question. Freemarker can help us too?

**Comment by betowebti** [comment]
Freemarker seemed easier...

Atenciosamente:

  Roberto Coelho

```
   JUG Leader
```

+5585 3037-4453 (gvt)

+5585 9635-1127 (tim)

+5585 9226-1748 (claro)
+5585 8185-6435 (vivo)

_"Comece fazendo o que é necessário, e depois o que é possível, de repente
você estará fazendo o impossível."  *
*"Um pessimista vê dificuldade em cada oportunidade. Um otimista vê
oportunidade em cada dificuldade."_

_"Start by doing what's necessary, then what is possible, suddenly you are
doing the impossible.""A pessimist sees difficulty in every opportunity. An
optimist sees opportunity in every difficulty."_

2014-01-29 Paulo A Junior notifications@github.com

**Comment by helio-frota** [comment]
@paulojribp @betowebti 
i don't know freemarker as "composite view pattern" , i guess is a template engine only right ?
i'm not sure about.

**Comment by helio-frota** [comment]
@paulojribp freemarker can help a lot with mail template messages.
to evict build this message on stringBuilder append on java code

**Comment by paulojribp** [comment]
Yeah.. I only use for this :/ sorry. I think wrong.
Let's use sitemesh, but let try to keep it simple to new devs can understand and help us with, right?!

**Comment by paulojribp** [comment]
An issue was created to make Sitemesh work. #17
