### ISSUE TITLE
Create a script to run Hurraa as service in linux based systems

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#104]
Create a script that put Hurraa as service. This will help end users and servers admin to run Hurraa. The main goal to this script is:
1. Put the start | stop | restart option to wildfly
2. Add as service in init.d folder
3. Start, stop and restart like the exemplo:
service hurraa start | service hurraa stop | service hurraa restart

**Comment by helio-frota** [comment]
Cool.
I started this on 14 February on my blog feel free to use
http://eprogramming.github.io/blog/2014/2/14.html

**Comment by helio-frota** [comment]
Esse script vem por default no wildfly, fechando a issue
