### ISSUE TITLE
What do you think Junit Controllers Mockito

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#105]
I found this what do you think ?

http://yuriadamsmaia.wordpress.com/2011/08/05/com-vraptor-e-mockito-e-muito-mais-facil-testar/

**Comment by paulojribp** [comment]
I don't like Controllers test. I believe if you need to test controllers is because to many logic was there. So, I suggest to avoid controller test since we don't put logic on controllers.

**Comment by helio-frota** [comment]
Great. Waiting for the position from others commiters of the project. @efraimgentil, @danielsoro and @emanuelmm

**Comment by efraimgentil** [comment]
Unit test in a controller is not really necessary, unless you want to validate some flow logic or trigger a validator, but for that, i would prefer to use acceptance tests.

**Comment by emanuelmm** [comment]
weeeeell, i agree with @paulojribp and @efraimgentil . In the theory is not necessary

**Comment by helio-frota** [comment]
Great @danielsoro and @all 
3 committers don't like so close this or wait @danielsoro ?

**Comment by danielsoro** [comment]
Then, I don't see problem with mockito, I like it, but What the graus of the test? Integration or Unit? I don't see problem with only unit test, is better that nothing. :)

**Comment by paulojribp** [comment]
I believe this is enough, right? Closing this issue.
