### ISSUE TITLE
Owner(s) do projeto

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#106]
Senhores, gostaria de levantar aqui a questão iniciada na lista sobre o Owner do projeto. Eu creio que podemos ter um owner mas sou contra ele ser uma única pessoa tendo em vista o tanto que o projeto tem de participação. Assim, sugiro que levantamos sugestões para decidir isso.
Outra coisa, o projeto deve ser do CEJUG. Os owners só iram ser os caras do cejug que decidem sobre uma questão específica quando essa não puder ser decidida por todos os commiters. Isso ajuda na confiança do projeto. Dizer que o projeto é do cara X e ele vai decidir pelo projeto, ele pode um dia papocar o projeto e pronto, tudo morre e eu fico na mão. Sendo do grupo, assim como o footprint, por mais que o cara que mais cuidava do projeto não continue, o projeto continua lá e pronto para novas contribuições.
Assim, sugiro ter um grupo de 3 pessoas para owners e não apenas 1

**Comment by helio-frota** [comment]
Concordo @paulojribp
TomEE por exemplo não tem só 1 não.

**Comment by helio-frota** [comment]
"Outra coisa, o projeto deve ser do CEJUG"
Exatamente assim como os projetos são da Apache, perfeito.

**Comment by danielsoro** [comment]
Sigo a mesma linha do Helio. Concordo e acho que você tem razão Paulo. :-)

On Thu, Feb 20, 2014 at 4:46 PM, eprogramming notifications@github.comwrote:

> "Outra coisa, o projeto deve ser do CEJUG"
> Exatamente assim como os projetos são da Apache, perfeito.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/106#issuecomment-35661174
> .

## 

_Daniel Cunha_
Site http://danielsoro.com.br - G
http://github.com/danielsoroitHubhttp://github.com/danielsoro-
LinkedIn http://www.linkedin.com/in/danielvlcunha

**Comment by htmfilho** [comment]
+1 Pra simplficar, eu acho que os owners devem ser sempre os JUG leaders em
atividade. Deixou de ser JUG leader, deixa de ser owner. Um negócio assim.
Mas é só uma sugestão. ;-)

On Thu, Feb 20, 2014 at 8:47 PM, Daniel Cunha notifications@github.comwrote:

> Sigo a mesma linha do Helio. Concordo e acho que você tem razão Paulo. :-)
> 
> On Thu, Feb 20, 2014 at 4:46 PM, eprogramming notifications@github.comwrote:
> 
> > "Outra coisa, o projeto deve ser do CEJUG"
> > Exatamente assim como os projetos são da Apache, perfeito.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cejug/hurraa/issues/106#issuecomment-35661174>
> > .
> 
> ## 
> 
> _Daniel Cunha_
> Site http://danielsoro.com.br - G
> http://github.com/danielsoroitHubhttp://github.com/danielsoro-
> LinkedIn http://www.linkedin.com/in/danielvlcunha
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/106#issuecomment-35661232
> .

## 

Hildeberto Mendonça, Ph.D
Blog: http://www.hildeberto.com
Twitter: https://twitter.com/htmfilho http://www.cejug.org

**Comment by helio-frota** [comment]
+1 @htmfilho

**Comment by efraimgentil** [comment]
+1 apoiado companheiros utrajovens
+1 @htmfilho https://github.com/htmfilho  também

2014-02-20 17:10 GMT-03:00 eprogramming notifications@github.com:

> +1 @htmfilho https://github.com/htmfilho
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/106#issuecomment-35663521
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github https://github.com/efraimgentil
LinkedInhttp://www.linkedin.com/profile/view?id=215608595&trk=nav_responsive_tab_profile_pic

**Comment by emanuelmm** [comment]
concordo com @htmfilho mas acho que a regra poderia ser o seguinte:
Todo JugLider é owner dos projetos, mas nem todo owner de projeto é um JugLider, assim os caras mais ativos em um determinado projeto poderiam assumir esse papel em um determinado projeto.

**Comment by betowebti** [comment]
+1 @htmfilho, discordo @emanoelcordeiro, porque é necessária a manutenção
do repositório. Não estou dizendo que vai acontecer, mas vai que esse owner
"papoque" o repo?! Ele precisaria ter direitos administrativos sobre a
conta do cejug no git e tais diretrizes somente se for jugleader.

Atenciosamente:

Roberto Coelho

JUGLeader CEJUG | Front-End Dev at CCIA | betoweb.com.br

Em 20 de fevereiro de 2014 20:36, Emanuel Cordeiro <notifications@github.com

**Comment by helio-frota** [comment]
Para quem não ficou sabendo da discussão antiga, a proposta antes era que cada um era dono do projeto e o cejug apoiava "Projetos apoiados pelo CEJUG". Isso foi discutido para que o CEJUG não se transformasse em uma "Apache" em termos de muita burocracia. Mas na filosofia antiga o dono pode papocar, eu mesmo papoquei projetos pessoais varias vezes, pessoas fazem isso todos os dias ao redor do mundo e não tem nada de pecado nisso.  

Sobre perder tudo é mais dificil pois cada cópia de trabalho distribuida do git é um repostório, mas isso é outro assunto.

Engraçado que eu repassei muita coisa que pesquisei e acho que pouca gente notou, apagar projeto, licenças, vender, pesquisa sobre prazos de contribuição e committer , exemplos de como funcionam as coisas por ai em projetos maiores pois estou com tempo livre para pesquisar esses fatores, pesquisar opiniões seja mandando email ou assistindo entrevistas/lendo faqs de owners de projetos bem maiores e conhecidos para compartilhar com o grupo e tentar seguir esse modelos. 

Acho que se o projeto é do CEJUG os owners deveriam ser os jug leaders mesmo como propos o @htmfilho. Mas não por caso de papocar projeto mas por questão de ser projeto do grupo mesmo. No footprint eu sou um committer mas o projeto é do CEJUG, por exemplo se um jug leader informar que o footprint não vai usar TomEE ou Bootstrap, por mim tranquilo, enquanto não disserem nada eu vou programar.

**Comment by paulojribp** [comment]
Essa discussão é complicadinha :). Ser os jugleaders é complicado porque nem sempre um jugleader vai estar por dentro do projeto. Alguns momentos tem jugleaders que se afastam mais por problemas pessoas e outros momentos voltam e algum outro se afasta e assim vai. Isso é prejudicial ao projeto. Eu estou mais de acordo com a proposta do @emanuelmm. O fato do projeto ser do cejug não quer dizer que o owner tem que ter a chave do repositório e direitos administrativos. Até dá para fazer isso por repositório, sem precisar dar a ele direito de owner da organization @betowebti. Mas nem precisa disso. O owner tem mais papel de definir com o grupo, levantar discussões e quando for preciso esses _owners_ poderão decidir sem consultar o grupo em coisas mais polêmicas ou difícil para uma votação.
Eu vou com o @emanuelmm mesmo. Acho que o mais justo é os mais ativos do projeto mesmo que não sejam jugleaders. Eles são do cejug e isso já é motivo suficiente para o cara ter direito no repo.
JugLeader não precisa concentrar todas as responsabilidades neles não.

**Comment by betowebti** [comment]
Então eu entendi errado @paulojr. No meu entendimento owner é o dono, o
cara com as chaves do portão. O que eu não concordo é definir aqui
https://github.com/organizations/cejug/settings/owners, mas no projeto, sem
problemas.

Atenciosamente:

Roberto Coelho

JUGLeader CEJUG | Front-End Dev at CCIA | betoweb.com.br

Em 20 de fevereiro de 2014 23:46, Paulo A Junior
notifications@github.comescreveu:

**Comment by paulojribp** [comment]
Isso @betowebti, ele não precisa ser Owner da organization CEJUG para administrar um projeto. Criei um grupo chamado cejug-owners lá que permite o cada administrar o projeto mas ele não consegue fazer nada com o grupo. Ah, criei só para teste, você pode ver na própria descrição do github. Ainda estou esperando a decisão de todos para podermos decidir essa parte.
Vamos fazer o seguinte sendo mais objetivos. Quem é a favor de ser os JugLeaders vota **+1**, quem é a favor de ser escolhido 3 entre os commiters vota **-1**. O +1 é para os jugleaders por ser a primeira proposta colocada aqui que foi a do @htmfilho. Resumindo:

JugLeaders são os Owners: **+1**
Escolher dentre os commiters: **-1**

Daí pra frente, creio que deve seguir o modelo do cejug, Meritocracia. Se 1 owner quer deixar de ser owner e quer ser apenas commiter ou vai sair mesmo do projeto. Os outros dois escolhem o próximo owner também dentre os commiters mais ativos. Se 1 owner não está mais ativo e deixa de colaborar com o projeto por mais de 3 meses deixa de ser owner e os 2 que ficaram escolhem o próximo.

**Comment by helio-frota** [comment]
+1

**Comment by htmfilho** [comment]
Vocês. Poderiam, por favor, submeter a decisão final sobre o assunto para o regimento?

Lembro também que o CEJUG tem um Fork do Yougi e por isso é owner daquele fork. Vocês podem criar funcionalidades que não existem no Yougi original. Toda vez que eu vou reimplantar o Yougi no servidor do CEJUG eu atualizou o fork do CEJUG, gero o pacote a partir de lá.

**Comment by clairtonluz** [comment]
-1

**Comment by efraimgentil** [comment]
-1

2014-02-21 12:36 GMT-03:00 Clairton notifications@github.com:

> -1
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/106#issuecomment-35741072
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github https://github.com/efraimgentil
LinkedInhttp://www.linkedin.com/profile/view?id=215608595&trk=nav_responsive_tab_profile_pic

**Comment by paulojribp** [comment]
Ainda está faltando alguns votarem. @danielsoro, @emanuelmm e @betowebti, acho que falta só vocês dos commiters e JL.

**Comment by betowebti** [comment]
-1

Atenciosamente:

Roberto Coelho

JUGLeader CEJUG | Front-End Dev at CCIA | betoweb.com.br

Em 23 de fevereiro de 2014 16:21, Paulo A Junior
notifications@github.comescreveu:

**Comment by danielsoro** [comment]
-1

**Comment by emanuelmm** [comment]
-1

**Comment by paulojribp** [comment]
A decisão foi pela escolha dos owners poder ser entre os commiters do projeto. Abrindo outra issue para decidirmos os nomes.
