### ISSUE TITLE
Escolha dos owners do Hurraa

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#108]
De acordo com a #106, os owners serão decididos entre os commiters. Assim, votem colocar os nomes de quem você acharia que deveria ser owner. Coloque o nome de até 3 commiters. Os commiters são:
@htmfilho 
@efraimgentil 
@danielsoro 
@eprogramming 
@emanuelmm 
@paulojribp

Exemplo de votação:
Eu voto em
Voto 1: @candidato1
Voto 2: @candidato2
Voto 3: @candidato3

Lembrando que mais de 3 votos do quarto em diante será desconsiderados. Ao final, os 3 mais votados serão os owners :)

Vamos votar.

**Comment by htmfilho** [comment]
Voto 1: @efraimgentil 
Voto 2: @eprogramming 
Voto 3: @paulojribp

**Comment by danielsoro** [comment]
Voto 1: @efraimgentil
Voto 2: @eprogramming
Voto 3: @paulojribp

**Comment by efraimgentil** [comment]
Voto 1: @htmfilho 
Voto 2: @eprogramming 
Voto 3: @danielsoro

**Comment by emanuelmm** [comment]
Voto 1: @efraimgentil
Voto 2: @eprogramming
Voto 3: @paulojribp

**Comment by paulojribp** [comment]
Voto 1: @efraimgentil 
Voto 2: @danielsoro 
Voto 3: @eprogramming

**Comment by helio-frota** [comment]
Voto 1: @paulojribp
Voto 2: @efraimgentil
Voto 3: @htmfilho

**Comment by paulojribp** [comment]
Legal galera, valeu por votarem. Como todos os commiters do projeto já votaram, então vamos encerrar mesmo outros não tendo participado.
O time de Owners do projeto será formado por:
Efraim (@efraimgentil) com 5 votos
Hélio (@eprogramming) com 5 votos
Paulo Jr (@paulojribp) com 4 votos

Valeu galera.. as discusões de como será essa direção de owners acho que pode ser feita por e-mail entre os owners agora não é? Qualquer sugestão favor enviar a um dos owners :) Vamos botar esse hurraa pra bombar :D
