### ISSUE TITLE
Validate the dev setup environment again

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#114]
just drop all and start the setup again. Submit a screenshot from the app running here as comment.

1) delete .m2/repository content
2) delete the project on eclipse
3) delete database and wildfly configuration
4) setup all again
5) put screenshot working or create issue if not working

**Comment by helio-frota** [comment]
After clone and import the project on eclipse the 21.1MB into .m2/repository directory and the project still with compilation errors. Doing mvn eclipse:eclipse now and more download...

**Comment by helio-frota** [comment]
After mvn eclipse:eclipse 88.6 MB into .m2/repository directory, refresh on eclipse and compilation errors gone.

**Comment by helio-frota** [comment]
After database, wildfly setup can't run the project due :
Caused by: java.lang.NoClassDefFoundError: br/com/caelum/vraptor/validator/DefaultValidator

![26](https://f.cloud.github.com/assets/6443576/2333320/0b212886-a469-11e3-8521-255f17a7e58b.png)

**Comment by felipewmartins** [comment]
I did the same steps performed by @eprogramming, the only difference was in the execution of mvn, where did the eclipse import: import -> existing maven project. I managed to run it with no problem.

**Comment by helio-frota** [comment]
This too:
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ForwardingMap
Caused by: java.lang.ClassNotFoundException: com.opensymphony.sitemesh.webapp.SiteMeshFilter from [Module "deployment.hurraa.war:main" from Service Module Loader]

**Comment by helio-frota** [comment]
@felipewmartins  i did this too.
i did the import from eclipse but i run the mvn eclipse:eclipse from the console
