### ISSUE TITLE
Error after navigating the Hurraa

### ISSUE THREAD

**Issue by felipewmartins** [cejug/hurraa#115]
I noticed that after running some navigations in Hurraa, including changing language exit a screen and another, and try to include a model of equipment, an exception was thrown by the system.

![erro-hurra2](https://f.cloud.github.com/assets/5208478/2340886/9efe37fc-a4cc-11e3-83f1-3f32cddba87f.png)

**Comment by efraimgentil** [comment]
@felipewmartins, i'm trying to reproduce the error but without success, can you give a step by step guide so we can reproduce the error?

**Comment by felipewmartins** [comment]
It happened as follows @efraimgentil : 
If I click "add" on the equipment model and after this I exit the screen and go to another menu, for example: Equipment. And click "add", the exception is thrown.

**Comment by felipewmartins** [comment]
I was testing in CR1 WF ​​version, the final version and the problem does not occur. Validated.
