### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by efraimgentil** [cejug/hurraa#123]
Login screen that will ask for Username and Password to proceed.

Obs: don't need block the access to rest of the system yet

**Comment by paulojribp** [comment]
Great @efraimgentil, I was doing that. I have made a little part of it and I will keep doing it. Thanks for the register.

**Comment by helio-frota** [comment]
hi all , any progress ?

**Comment by paulojribp** [comment]
I have decided that we are going to use Apache Shiro. :D PicketLink needs too much configuration.

**Comment by felipewmartins** [comment]
Any progress??
