### ISSUE TITLE
User form - password confirmation field

### ISSUE THREAD

**Issue by diogodias86** [cejug/hurraa#127]
the user form doesn't have a password confirmation field.

**Comment by diogodias86** [comment]
hi guys, what do you think of putting a password confirmation field in the login form and validate of course?

**Comment by efraimgentil** [comment]
you mean in the creation of the user? would be nice =)

**Comment by helio-frota** [comment]
hi guys, what do you think of putting a password confirmation field in the login form and validate of course?

+1

**Comment by diogodias86** [comment]
ok, i'll do this!!

yeah, @efraimgentil in the creation of the user.

**Comment by efraimgentil** [comment]
Goo job @diogodias86, going to close the inssue!

**Comment by diogodias86** [comment]
thanks, @efraimgentil !!
