### ISSUE TITLE
Sectors list - Boolean columns values

### ISSUE THREAD

**Issue by diogodias86** [cejug/hurraa#132]
Change the columns "Meets Called" and "Active" to write yes or no instead true or false.

**Comment by diogodias86** [comment]
do you think that is a good idea create a custom tag for this?

**Comment by efraimgentil** [comment]
I don't think this is a problem for now, we would only use this two times, ofcourse if this becomes a problem later would be nice to have a centralized and reusable way to handle it.

**Comment by diogodias86** [comment]
ok, i'll put only on the page.

**Comment by efraimgentil** [comment]
Closing, great job @diogodias86
