### ISSUE TITLE
CRUD Occurrence Status

### ISSUE THREAD

**Issue by efraimgentil** [cejug/hurraa#137]
CRUD for the new entity OccurrenceStatus

Will have the fields
- Integer   id
- String     name
- boolean active

**Comment by paulojribp** [comment]
Great job @efraimgentil. Maybe we can make some announcements on the cejug list to other members can contribute with it. What do you think?

**Comment by efraimgentil** [comment]
Yeah would be great, i'm studing ocomon right now so we can create more issues to they (and us) contribute.
