### ISSUE TITLE
Update Occurrence

### ISSUE THREAD

**Issue by efraimgentil** [cejug/hurraa#138]
The user should be able to update occurrence, like the status, add comments, register the progress of the occurrence or any difficulty being faced. Every change should be registered in the occurrence, there is a picture that should be used as example.

Any suggestion would be welcome
![example](https://cloud.githubusercontent.com/assets/2091945/2785541/e6f4cdbc-cb57-11e3-84b6-4db2b6b81666.jpg)

**Comment by helio-frota** [comment]
+1 go ahead

**Comment by efraimgentil** [comment]
Working on it
