### ISSUE TITLE
Create a wiki page to teach how to made Wildfly as Unix System Service

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#141]
How the issue #104 says, the script will be so useful to made something like:
`service wildfly start` or `service wildfly stop` and made the WildFly starts with the operational system.

The wiki page's will help Hurraa users to use the script that comes with WildFly cited by @eprogramming on issue #104.

**Comment by helio-frota** [comment]
Hi @paulojribp i currently put another server in production here, this is the step-by-step

later i'm going to commit on wiki and translate to english.

( yum install java-1.7.0-openjdk-devel )
utilizar o JDK , o script procura pelo jdk
ou altere o script na unha.

1) cd /opt
2) unzip wildfly-8.0.0.Final.zip
3) mv wildfly-8.0.0.Final wildfly
4) cp wildfly/bin/init.d/wildfly.conf /etc/default/
5) nano /etc/default/wildfly.conf

descomentar ( e caso necessário configurar) as seguintes variáveis:
    JAVA_HOME, 
    JBOSS_HOME, 
    JBOSS_USER, 
    JBOSS_MODE,
    JBOSS_CONFIG,
    STARTUP_WAIT,
    SHUTDOWN_WAIT,
    JBOSS_CONSOLE_LOG

6) cp wildfly/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly
7) chkconfig --level 345 wildfly on
8) adduser wildfly
9) gpasswd -a wildfly wildfly
10) chown wildfly.wildfly -R wildfly/
11) habilitar portas para acesso externo:
    nano wildfly/standalone/configuration/standalone.xml
    modificar 127.0.0.1 por 0.0.0.0

12) service wildfly start
13) libere a porta 8080 no iptables
14) acesse http://IP:8080 para validar
15) service wildfly stop
16) faça o reboot para validar o daemon

**Comment by helio-frota** [comment]
https://github.com/cejug/hurraa/wiki/Wildfly-server-setup

**Comment by paulojribp** [comment]
Great work @eprogramming.
