### ISSUE TITLE
Any problems with encoding ?

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#144]
Hi, i saw this:

``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>2.4</version>  
     <configuration>                    
          <encoding>ISO-8859-1</encoding>
     </configuration>
</plugin>
```

and this :

``` xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```
- So why we need both encodings ? 

Or 
- Why we need maven-resources-plugin ?

thanks

**Comment by efraimgentil** [comment]
@eprogramming  i believe this was added to handle the issue #119

**Comment by danielsoro** [comment]
I think that default encoding is UTF-8.

**Comment by paulojribp** [comment]
@efraimgentil, you are right. This was the beginning of this updates, but I prefer to set all to UTF-8. So, if we can use all with utf-8, my vote is to remove this block of code @eprogramming.

**Comment by helio-frota** [comment]
:+1:

**Comment by efraimgentil** [comment]
+1 i agree with @paulojribp
