### ISSUE TITLE
messages_pt_BR.properties using iso-8859-1 encoding

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#151]
use this command to check file encoding:

``` shell
[hf@hulk resources]$ file -bi messages_pt_BR.properties 
text/plain; charset=iso-8859-1
```

When open it with utf8 editor we get this:

menu.incident=Ocorr�ncias
menu.incident.open=Abrir Ocorr�ncia

**Comment by paulojribp** [comment]
I agree if this @eprogramming. But I don't like to use `\u00e3` for brazilian characters, I prefer use natural text:

```
label.no=N\u00e3o
#instead
label.no=Não
```

This can work properly with UTF-8. But, for now, lets keep your way so we can focus our effort on really important things.
Thanks.

**Comment by paulojribp** [comment]
PS: Sorry for not responding yesterday on IRC. I was teaching, and keep IRC open only for conversation registry.

**Comment by helio-frota** [comment]
``` shell
native2ascii -encoding utf8 messages_pt_BR.properties x.properties
```

http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/native2ascii.html

jstl fmt (resource bundle) expects iso-8859-1 instead of UTF-8, is technical issue

**Comment by paulojribp** [comment]
no problem.
