### ISSUE TITLE
Simple injection usage and no more @Deprecated annotation 

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#153]
From:

``` java
@Controller
public class IndexController {

    private Result result;

    @Deprecated
    public IndexController() {}

    @Inject
    public IndexController(Result result) {
        this.result = result;
    }

    @Path("/")
    public void index() {

    }

}
```

To:

``` java
@Controller
public class IndexController {

    @Inject
    private Result result;

    @Path("/")
    public void index() {

    }
}
```

**Comment by paulojribp** [comment]
The first one @eprogramming was discussed on the beginning of the project that it keeps the dependencies more clear and more useful for unit testing

**Comment by efraimgentil** [comment]
Yeah that was decided in the beginning, unfortunately CDI still have this problem with default constructors, but with the injection in the controller is easier to test and create mocks, so i kind of liked it

**Comment by paulojribp** [comment]
@eprogramming whats mean this Closed? Will keep constructors or injection on attribute?

**Comment by helio-frota** [comment]
hi @paulojribp good catch, i closed this.
well i'm going to use injection on attribute and wait / maybe research better approach for the tests.
