### ISSUE TITLE
Please use space and no tabs...

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#155]

**Comment by paulojribp** [comment]
I don't completely agree with this.

![tabsspacesboth](https://cloud.githubusercontent.com/assets/165086/3188342/c5da4ff2-ecb9-11e3-8c53-9a082981a671.png)

We have this discussion on my work and we agree with this:
http://www.emacswiki.org/SmartTabs
http://vim.wikia.com/wiki/Indent_with_tabs,_align_with_spaces

Any IDE can identify _tabs_ and _spaces_.

**Comment by helio-frota** [comment]
this causes horrible merge...more dificult to read

![merge](https://cloud.githubusercontent.com/assets/6443576/3189195/60d704d0-ecc1-11e3-8ca2-4c636081896c.png)

**Comment by helio-frota** [comment]
closing this.
