### ISSUE TITLE
sitemesh3 ?

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#160]
https://github.com/sitemesh/sitemesh3

**Comment by paulojribp** [comment]
Was any advantage with this update? If we have so, go ahead.
I saw that sitemesh was a little lazy. The release alpha was from 2011 - https://github.com/sitemesh/sitemesh3/releases. Only this year they have released. This is a little strange.

**Comment by helio-frota** [comment]
https://github.com/sitemesh/sitemesh2/
the version 2... last commit 3 years ago

**Comment by helio-frota** [comment]
since this is not part of hurraa goals , going to close this.
