### ISSUE TITLE
Include Sitemesh in the project

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#17]
The challenge is to keep it simple to new devs can understand and use it.

**Comment by helio-frota** [comment]
:+1:  perfect for now

**Comment by helio-frota** [comment]
![05](https://f.cloud.github.com/assets/6443576/2045494/77418586-89f9-11e3-8d2a-6f0a9aaedf93.png)

**Comment by helio-frota** [comment]
just to start small with sitemesh
1)header with menu and footer

**Comment by rsaraiva** [comment]
I am implementing an example for this.

**Comment by helio-frota** [comment]
@rsaraiva going to close this issue now jquery and css of purecss.io can be done !
well done !
