### ISSUE TITLE
Update README with configuration of env variable on Windows 

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#20]
How to set up env variable WILDFLY_HOME on Windows

**Comment by betowebti** [comment]
After the install Wildfly, press the Windows Key + R type the following comand: sysdm.cpl. When the Systems Properties window opens, click on tab advanced and press button Environment Variables.

![1](https://f.cloud.github.com/assets/698525/2059665/c2f7eae2-8bc5-11e3-9b5e-36a5b8a54420.jpg)

Then click "New", enter the variable name and path of the WildFly installation

![2](https://f.cloud.github.com/assets/698525/2059678/e3c68dc2-8bc6-11e3-8073-5101c669c05e.jpg)

After this, edit the PATH context append at the end of the line %WILDFLY_HOME%\bin;

![3](https://f.cloud.github.com/assets/698525/2059701/d47f30f0-8bc9-11e3-84a2-22560c8c68a5.jpg)

![4](https://f.cloud.github.com/assets/698525/2059702/db1d347a-8bc9-11e3-805e-086bca360900.jpg)

or open the prompt command window with Windows Key + R, typing "cmd" then type SET WILDFLY_HOME = C: \ your_installation_path after this type SET PATH=%WILDFLY_HOME%\bin
