### ISSUE TITLE
UTF-8 controller problem

### ISSUE THREAD

**Issue by efraimgentil** [cejug/hurraa#22]
I don't know if is only happening to me, but when i try to save something that have a accent it will be received in the controller with wrong characters

**Comment by htmfilho** [comment]
I had the same problem in another project and I had to add this filter https://github.com/htmfilho/architect/blob/master/src/main/java/com/hildeberto/architect/util/CharacterEncodingFilter.java :(

**Comment by helio-frota** [comment]
take care with botton-up approach:
0) SO
1) mysql
2) container
3) page encoding
4) not using ajax yet but this count too if the framework don't deal with it yet
*and wait if sitemesh don't include the issue too..

btw everything need/must to be UTF-8

**Comment by helio-frota** [comment]
just to share with others about mysql utf-8 and showing a sample of simple setup install of war app:

http://kawai.soliveirajr.com/mtw/Page/Installation/how-to-install-the-kawai-wiki

**Comment by efraimgentil** [comment]
I thought it may be the encoding in the database but i made the tests and
the mess start when the controller receive the request...

at the VRaptor Wiki they says to use this

<context-param>
    <param-name>br.com.caelum.vraptor.encoding</param-name>
    <param-value>UTF-8</param-value></context-param>

but didn't worked for me, i will try to see this later today

2014-01-31 eprogramming notifications@github.com:

> just to share with others about mysql utf-8 and showing a sample of simple
> setup install of war app:
> 
> http://kawai.soliveirajr.com/mtw/Page/Installation/how-to-install-the-kawai-wiki
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/22#issuecomment-33774123
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by paulojribp** [comment]
I'm going to ask people here about this. I have the same problem.

**Comment by helio-frota** [comment]
@efraimgentil here too.
going to investigate this.

**Comment by helio-frota** [comment]
@efraimgentil 
I debug the vraptor and the parameter followed without modification to the WF, maybe WF bug ? not respecting a custom request encoding ?

**Comment by helio-frota** [comment]
1) https://issues.jboss.org/browse/WFLY-2276
pelase see the comment "pull request sent. With this change you can configure encoding on listener(s)"

I did this without results...

@WebListener
public class EncodingListener implements ServletRequestListener {
     public void requestDestroyed(ServletRequestEvent servletRequestEvent) {
        ServletRequest servletRequest = servletRequestEvent.getServletRequest();
        try {
            servletRequest.setCharacterEncoding("UTF-8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }
     public void requestInitialized(ServletRequestEvent servletRequestEvent) { }
 }

2) https://issues.jboss.org/browse/UNDERTOW-136

maybe is really bug

**Comment by danielsoro** [comment]
Great Helio! :-)

**Comment by efraimgentil** [comment]
Nice helio, i will also take a look now =)

2014-01-31 Daniel Cunha notifications@github.com:

> Great Helio! :-)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/22#issuecomment-33859575
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by helio-frota** [comment]
Closing , waiting final version of WF.
feedback from @efraimgentil
