### ISSUE TITLE
Change datasource lib location

### ISSUE THREAD

**Issue by garcia-jj** [cejug/hurraa#32]
From hurraa readme:

> Get module wildfly here: https://docs.google.com/file/d/0B25_MAAKa3jEVFRCRnp5Sm9zZE0/edit and unpack in WILDFLY_HOME/modules/system/layers/base/com

But according Wildfly docs, all users libs must be located at `WILDFLY_HOME/modules`. `/system/layers/` location is only used by Wildfly.

**Comment by helio-frota** [comment]
@garcia-jj is true, thanks  !

"Install the JDBC driver as a core module"
"For example, using the MySQL JDBC driver above, you would create a directory structure as follows:    JBOSS_HOME/modules/com/mysql/main ... "

https://docs.jboss.org/author/display/WFLY8/How+do+I+migrate+my+application+from+AS5+or+AS6+to+WildFly

**Comment by betowebti** [comment]
If you put mysql libs in WILDFLY_HOME/modules/com/mysql/main you get the following error:

[standalone@localhost:9990 /] ./subsystem=datasources/jdbc-driver=com.mysql:add(driver-name="com.mysql", driver-module-name="com.mysql", driver-xa-datasource-class-name="com.mysql.jdbc.jdbc2.optional.MysqlXADataSource" )
{
    "outcome" => "failed",
    "failure-description" => "JBAS010441: Failed to load module for driver [com.mysql]",
    "rolled-back" => true
}

**Comment by garcia-jj** [comment]
Beto, attached have a printscreen of my pgsql driver under Wildfly modules location.

Check if your jar is located under modules/com/mysql/main and if module.xml properly defines the jar and your dependencies.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.1" name="org.postgresql">
 <resources>
 <resource-root path="postgresql-9.2-1002.jdbc4.jar"/>
 </resources>
 <dependencies>
 <module name="javax.api"/>
 <module name="javax.transaction.api"/>
 </dependencies>
</module>
```

![screenshot from 2014-02-01 23 55 17](https://f.cloud.github.com/assets/140387/2059422/663794be-8bad-11e3-89dd-f335c74a4db3.png)

**Comment by betowebti** [comment]
Thank's! Sorry, my fault. I extract to another folder... ;)

**Comment by helio-frota** [comment]
wait:
1) the focus is standalone mode  ?

"WildFly offers two modes: a traditional, single JVM, standalone mode, and a multi-JVM option, domain mode, which synchronizes configuration across any number of processes and hosts."

http://wildfly.org/about/

So the doc says:

"Install the JDBC driver as a deployment"
"In WildFly 8 standalone mode, you simply copy the JDBC 4-compliant JAR into the AS7_HOME/standalone/deployments directory. Here is an example of a MySQL JDBC driver installed as a deployment:

```
JBOSS_HOME/standalone/deployments/mysql-connector-java-5.1.15.jar"
```

https://docs.jboss.org/author/display/WFLY8/How+do+I+migrate+my+application+from+AS5+or+AS6+to+WildFly

**Comment by helio-frota** [comment]
we need to remember that the end user will do the installation of Hurraa project, so we need try to keep it simple right : D

2014 no more "run db and put war on deployment directory" and have fun ?

yougi is for user groups so  at least one end user is developer to take care of installation, now the end user may be a sysadmin or support guy that only knows backup, restore, MTA, hardware support, tivoli etc etc ... and nothing about "Wildfly".

[edited]
just my particular opinion : D

when hurraa release the first war , we need  "test" the installation process with a junior support if him cannot install so is not cool. Easy setup means many users too:

http://ocomonphp.sourceforge.net/empresas.php 

( gentoo vs ubuntu ?)
[/edited]

**Comment by betowebti** [comment]
so, we need to configure a .sh or .bat file like this:
https://gist.github.com/sukharevd/6087988 ?

**Comment by helio-frota** [comment]
Excelent idea @betowebti !

Yes !

Wee need script install !

**Comment by garcia-jj** [comment]
When put under `standalone/deployments`, only works in standalone mode. Put under `modules`, works for all modes.

**Comment by helio-frota** [comment]
@garcia-jj cool !

But for end user it needs to be invisible the math is simple, "no easy setup, no users" 
like LFS vs Linux mint , hurraa is for end user not developers.

this is possible ?

"dear end user: "
1) wget this script xpto
2) run and wait
3) access localhost:8080/hurraa

going to create a issue for something like this

**Comment by garcia-jj** [comment]
@eprogramming We have a mistake here. I was read the readme, and the location is wrong. So I only have suggested to change this location to use the right location. Using system layer works, but is not the right location.

But the project is yours. So you can decide what's the best for your users.

**Comment by htmfilho** [comment]
@garcia-jj when running in domain mode, all deployments are replicated among all WildFly instances. Since the JDBC Driver is a deployment it will be replicated and become available as well.

**Comment by htmfilho** [comment]
@eprogramming the main advantage of a module is the possibility of customising a WildFly installation, zip it, and make sure everybody works with the same configuration. They don't even need to deploy the driver. We can customise a WildFly for Hurraa and make it available for download.

**Comment by helio-frota** [comment]
@htmfilho " We can customise a WildFly for Hurraa and make it available for download."
So if is really possible we don't need the script install anymore ! Great and thanks for the tip !

**Comment by htmfilho** [comment]
I think the script is a plus. Both are very interesting strategies.

**Comment by paulojribp** [comment]
I agree @htmfilho .. or maybe we can have both. Distribute wildfly with hurraa inside and a script to configure important data like database name, user, password, etc .. on root folder named install.sh|bat and other to help client easily start|stop hurraa _start.sh|bat_ and _stop.sh|bat_

**Comment by helio-frota** [comment]
:+1:

**Comment by garcia-jj** [comment]
I think that providing a install script will help newbie users. This script can download Wildfly, extract the package, and configure the appserver using cli interface.

At this time I'm very busy with my personal project. But as soon as possible I'll happy to send a pull request with a suggestion for cli script.

Thank you guys.

**Comment by htmfilho** [comment]
PS: if your personal project is open source do not hesitate to ask the CEJUG community for contributions ;-)

**Comment by efraimgentil** [comment]
Great idea Garcia, i will finish the script today and provide for the project, thanks for the idea =)
