### ISSUE TITLE
Add Following GPLv3 Licence Text in Files

### ISSUE THREAD

**Issue by betowebti** [cejug/hurraa#39]
This file is part of Hurraa.

   Hurraa is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Hurraa is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Hurraa.  If not, see http://www.gnu.org/licenses/gpl-3.0.html.

**Comment by htmfilho** [comment]
I think you still have to add Copyright (C) 2014 CEJUG at the beginning.

**Comment by paulojribp** [comment]
Are we using GPLv3 on Hurraa? Maybe I lost some discussion about this.

**Comment by betowebti** [comment]
This is a same license in backward version.

Atenciosamente:

Roberto Coelho

JUGLeader CEJUG | Front-End Dev at CCIA | betoweb.com.br

**Comment by betowebti** [comment]
Let's leave the license as copyright for now and another time we will resume the discussion.

**Comment by htmfilho** [comment]
@paulojribp we had this discussion in CEJUG's mailing list: https://groups.google.com/d/msg/cejug/lhsTEU5w2-U/psQ0XOwxD0oJ

And then I replied here: https://groups.google.com/d/msg/cejug/lhsTEU5w2-U/_Y-LiQY8OVMJ, suggesting GPLv2, but we can go for GPL v3. They are almost the same.

**Comment by helio-frota** [comment]
So, just for share information until now all source code history remains unlicensed.
Better add soon, right ?

**Comment by helio-frota** [comment]
Sorry, i mean, about the copyright notice.
The gplv2 is on root directory.
