### ISSUE TITLE
Explain in the wiki how to use Liquibase to change the database

### ISSUE THREAD

**Issue by htmfilho** [cejug/hurraa#4]

**Comment by htmfilho** [comment]
Done: https://github.com/cejug/hurraa/wiki/Updating-the-Database-Structure

**Comment by paulojribp** [comment]
I have a doubt. Our propose is that new devs contribute with the project too, right? So, I think that the Wiki pages must to be written in Portuguese also. So, the project can have international contribution and new devs too. What do you think?

**Comment by betowebti** [comment]
I think that to have to languages: pt-BR and EN

Atenciosamente:

  Roberto Coelho

```
   JUG Leader
```

**Comment by htmfilho** [comment]
My experience on Yougi is that the Portuguese version gets outdated very fast because the contributor who was responsible for the translation is not that engaged in the project anymore.

I'm not translating because the work of writing is already enough work to deal with. Beginners can use Chrome to translate the page or use Google Translator.

**Comment by brunnooliveira** [comment]
I think that only in english, encourages the beginners to learn more fast
the language.

2014-01-31 Hildeberto Mendonça notifications@github.com:

> My experience on Yougi is that the Portuguese version gets outdated very
> fast because the contributor who was responsible for the translation is not
> that engaged in the project anymore.
> 
> I'm not translating because the work of writing is already enough work to
> deal with. Beginners can use Chrome to translate the page or use Google
> Translator.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/4#issuecomment-33794589
> .

## 

Brunno Gonçalves
85 8705.1940

Bacharel em Ciência da Computação
Análise e Desenvolvimento de Sistemas
Companhia de Água e Esgoto do Ceará - CAGECE

**Comment by danielsoro** [comment]
Yes @brunnooliveira. I don't speak english very well @htmfilho @paulojribp @eprogramming help me. :)

**Comment by helio-frota** [comment]
:+1:
