### ISSUE TITLE
Customise a WildFly for Hurraa and make it available for download.

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#40]
Again, easy setup for end users.

**Comment by helio-frota** [comment]
The issue of script do the download, and we don't know if can put hurraa on cejug server BTW suggestions ?

**Comment by htmfilho** [comment]
Hurraa should be so simple to install that CEJUG doesn't even need to provide a demo version ;-) The hardest part of the installation is installing and configuring the database. If you configure WildFly and deploy Hurraa on it, you just need to stop the server, zip everything and make it available for download. It makes Hurraa as simples as Wordpress to be installed ;-)

**Comment by helio-frota** [comment]
zip everything and make it available for download. It makes Hurraa as simples as Wordpress to be installed ;-)

@htmfilho Cool , easy setup means more users : ]

**Comment by felipewmartins** [comment]
What do you think of creating an installer for IzPack Hurra using?

**Comment by helio-frota** [comment]
going to close this too, vagrant is better. we need to focus more on app.

**Comment by paulojribp** [comment]
Sorry @eprogramming, I disagree. Vagrant is not so simple and a end user (not programmer) may not know how to use. I will keep this issue open and I completely agree with @htmfilho. Is so easy to use make a simple pack with Wildfly to download all together.

**Comment by helio-frota** [comment]
@paulojribp yes sure.
the main focus is the app now, to get the things working

**Comment by helio-frota** [comment]
hi,
Unfortunately I can't work on this issue.
My laptop was stolen around ~2015 and I don't own this github handle: `eprogramming` anymore.
Also I don't remember a lot of java things.
