### ISSUE TITLE
Create sample crud with ajax and default html5 tags

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#42]
Just to start a discussion

( discussion started with @efraimgentil  on IRC )

**Comment by helio-frota** [comment]
https://github.com/cejug/hurraa/issues/35

**Comment by paulojribp** [comment]
@eprogramming I believe that this issue can continue (or open another) to make a ajax request completely in html5 or really use jquery. My idea is to make a simple ajax request (not crud) to have an example on how to make ajax. What do you think?
