### ISSUE TITLE
CRUD Equipment

### ISSUE THREAD

**Issue by efraimgentil** [cejug/hurraa#46]
1. Should have the fields 
   - Long id, primary key
   - String serial_id, not null , unique 
   - Date endOfWarranty 
   - Date lastMaintenance
   - String maintenanceDescription
   - Model model, not null, https://github.com/cejug/hurraa/issues/45 "Many equipments can have one model"
2. Should validate on update/insert and show errors messages if any
3. Should update liquibase with new table and respective fields and constraints

**Comment by emanuelmm** [comment]
i'm working in this!

**Comment by emanuelmm** [comment]
Start the job in the issue below:
Issue #68

**Comment by efraimgentil** [comment]
This issue can be closed ?

**Comment by emanuelmm** [comment]
I guess that not, because the item 2 wasn't done yet

**Comment by paulojribp** [comment]
Are you doing it or you need some help?

**Comment by emanuelmm** [comment]
I created only the crud... i'm going to this task soon

**Comment by emanuelmm** [comment]
Completed with the issue #107.
