### ISSUE TITLE
Problem with version tag pom.xml

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#6]
'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ line 6, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

please make a pull to fix the version

from
<version>0.1.SNAPSHOT</version>
to
<version>0.0.1-SNAPSHOT</version>
or 
<version>0.0.1</version>

**Comment by paulojribp** [comment]
Hi @eprogramming,

If you want, you can fix it. It's a minor issue but can be the first way you participate the project.
If you don't, let me know then I will fix it.

Thanks

**Comment by helio-frota** [comment]
Hi 

the .gitignore file from @danielsoro is needed because target folder included.

https://github.com/danielsoro/hurraa/commit/3032ffd00c8965eafa58e6fe38b42951f6fc7636

comment updated i need to keep focused, sorry. : ]

**Comment by betowebti** [comment]
+1 kkkk

Atenciosamente:

  Roberto Coelho

```
   JUG Leader
```

+5585 3037-4453 (gvt)

+5585 9635-1127 (tim)

+5585 9226-1748 (claro)
+5585 8185-6435 (vivo)

_"Comece fazendo o que é necessário, e depois o que é possível, de repente
você estará fazendo o impossível."  *
*"Um pessimista vê dificuldade em cada oportunidade. Um otimista vê
oportunidade em cada dificuldade."_

_"Start by doing what's necessary, then what is possible, suddenly you are
doing the impossible.""A pessimist sees difficulty in every opportunity. An
optimist sees opportunity in every difficulty."_

2014-01-27 eprogramming notifications@github.com

**Comment by paulojribp** [comment]
Great Helio (@eprogramming) :D
That pull request fix it. Thanks.
