### ISSUE TITLE
Add ValidationMessages for bean validation with portuguese messages

### ISSUE THREAD

**Issue by efraimgentil** [cejug/hurraa#61]
1. Add ValidationMessages.properties to the classpath resources
2. Add the portuguese translated messages 
3. Find a way to inject the validationMessages bundle to the controllers if needed

**Comment by htmfilho** [comment]
You can find a solution to access the bundle at the controller level in Yougi's source: https://github.com/htmfilho/yougi/blob/master/src/main/java/org/cejug/yougi/util/ResourceBundleHelper.java

**Comment by efraimgentil** [comment]
Thanks for the tip Hildeberto, i made a diferent solution but also works as
a charm, i made a qualifier and a producer so when i
put @ValidationMessages in a attribute or a parameter of the
ResourceBundle,  it will trigger the producer and provide de
ValidationMessages.properties bundle.
If i do not use the annotation it will inject the messages.properties
bundle....

2014-02-06 5:03 GMT-03:00 Hildeberto Mendonça notifications@github.com:

> You can find a solution to access the bundle at the controller level in
> Yougi's source:
> https://github.com/htmfilho/yougi/blob/master/src/main/java/org/cejug/yougi/util/ResourceBundleHelper.java
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/61#issuecomment-34300368
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by efraimgentil** [comment]
Done  https://github.com/efraimgentil/hurraa/commit/59bc7dbeca2c8bbd1a338f3078a6932634238d63
