### ISSUE TITLE
Better main screen presentation 

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#66]

**Comment by helio-frota** [comment]
Sugestions ?

**Comment by efraimgentil** [comment]
Maybe a resume of what is new in the version, and what is coming next.
A suggestion box....

2014-02-11 22:54 GMT-03:00 eprogramming notifications@github.com:

> Sugestions ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/66#issuecomment-34830916
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github: efriamgentil https://github.com/efraimgentil

**Comment by helio-frota** [comment]
Yep, good suggestion.
So this issue is able to be done now.

**Comment by paulojribp** [comment]
I believe we need to avoid abstract issues like this. So, what is a better main screen presentation?
For me, is a pretty screen with fantastic css to the main screen be so cute. :) But, can be better functionalities, like suggested by @efraimgentil. So, let's create issues more specific, like:
"Put welcome text on main screen" or "Define what content will be on main screen". Nevertheless, will be a little abstract :(. But I believe you can understand the idea, right?

**Comment by helio-frota** [comment]
@paulojribp Yep
