### ISSUE TITLE
The main language is pt_BR ?

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#79]
If the project follows the ocomon so the market is Brasil and primary i18n language needs to be pt_BR not en_US right ?

**Comment by htmfilho** [comment]
Right. Primeiro focamos no Brasil.

On Fri, Feb 14, 2014 at 1:02 AM, eprogramming notifications@github.comwrote:

> If the project follows the ocomon so the market is Brasil and primary i18n
> language needs to be pt_BR not en_US right ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/79
> .

## 

Hildeberto Mendonça, Ph.D
Blog: http://www.hildeberto.com
Twitter: https://twitter.com/htmfilho http://www.cejug.org
