### ISSUE TITLE
Use NamedQuery in Entity Level

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#94]
Hi,
This issue is to know your opinion about the use of `@NamedQueries` annotation.

I disagree with it because it soiled the vision of the class. When the time pass it tends to grow up and the class became every time more dirty. And another thing is that the class be directly part of the DAO layer. If we want to modularize Hurraa in the future, we will have queries where we maybe don't need, and the jars will be kept in both projects only for compilation reasons.

**Comment by htmfilho** [comment]
I don't like `@NamedQueries` either. I know it has an advantage which is to be pre-compiled during compilation time, improving a bit the performance, but I think it is bad for readability.

**Comment by helio-frota** [comment]
I don't like @NamedQueries either. 

:+1: 

Looks like "DonaFlorindaPattern"

**Comment by paulojribp** [comment]
Great. Waiting for the position from others commiters of the project. @efraimgentil, @danielsoro and @emanuelmm

**Comment by efraimgentil** [comment]
Use or do not, i don't see a problem, i used for the performance reasons,
but if we will not use i don't see a problem neither.

2014-02-17 12:33 GMT-03:00 Paulo A Junior notifications@github.com:

> Great. Waiting for the position from others commiters of the project.
> @efraimgentil https://github.com/efraimgentil, @danielsorohttps://github.com/danielsoroand
> @emanuelmm https://github.com/emanuelmm
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cejug/hurraa/issues/94#issuecomment-35293249
> .

## 

Atenciosamente,
Efraim Gentil - @efraimgentil https://twitter.com/efraimgentil
Github https://github.com/efraimgentil
LinkedInhttp://www.linkedin.com/profile/view?id=215608595&trk=nav_responsive_tab_profile_pic

**Comment by emanuelmm** [comment]
the deploy validation is good because we can see error before to use the query, but the negative point is really the project growth.
I think that in our case there aren't reasons to use.

**Comment by danielsoro** [comment]
I don't like @NamedQueries
