### ISSUE TITLE
Update VRaptor to 4.0.0-RC1

### ISSUE THREAD

**Issue by paulojribp** [cejug/hurraa#95]
The VRaptor version 4.0.0-RC1 has arrive and we need to update it on Hurraa:
http://www.guj.com.br/noticias/142-vraptor-4-agora-na-versao-rc1

**Comment by helio-frota** [comment]
After update i see this error:

Archive for required library: '.m2/repository/br/com/caelum/vraptor/4.0.0-RC1/vraptor-4.0.0-RC1.jar' in project 'hurraa' cannot be read or is not a valid ZIP file hurraa  Build path Build Path Problem

I removed the directory /br/com/caelum/vraptor/ and iogi , then problem gone.

**Comment by felipewmartins** [comment]
I had the same problem, after making the deletion of folders named by @eprogramming  I was in the project -> maven -> update project. And the error has been resolved.

**Comment by paulojribp** [comment]
The main solution is what @felipewmartins commented. The problem is only eclipse maven plugin. What you do @eprogramming solves too because maven will download the jar again.

**Comment by helio-frota** [comment]
@paulojribp just to share the information, the main solution was remove the jars from directory.
mvn clean package -U do not update here 
so @felipewmartins did the hard delete on jars and then update project on eclipse.
this was discussion on IRC : ]

**Comment by paulojribp** [comment]
I don't need to do anything of this. Only update pom.xml and run maven -> update project. Simple like that.

**Comment by helio-frota** [comment]
yep, but on my machine and machine of @felipewmartins this error happened so we both decided to share the information to help others contributors.

**Comment by paulojribp** [comment]
:+1:
